### PR TITLE
Error handling and New Line for c0de copy pasta!

### PR DESCRIPTION
**Pull request by jordantrizz**
* Added in error handling due to bad API key or potentially a low funded account.
* Added a newline before response as to help with copy and pasting code :)

### CODE REVIEW

**Comment by jordantrizz** [comment]
I needed this to debug why my API key wasn't working, and then needed to copy and paste code but thought a new line would help.

**Comment by 0xacx** [comment]
Thank you very much for this PR! 🙏 
I used your suggestion and added an error handling function in chat and image generation. ✌️ 
About the newline, I really prefer it the way it is, as it intuitively feels more like a chat conversation, although I understand that for code a new line makes things easier to copy.
Cheers!

**Comment by jordantrizz** [comment]
No worries about the new line.

Have you thought about a mode where you can pass the question via arguments and have the answer returned to stdout?

**Comment by 0xacx** [comment]
Yes, that has been on my mind, the use case being that it would allow you to pipe the response to another command/script. In practice I didn't have the need for that functionality yet. I might add it in the future though.

**Pull request closed without merging**
